### ISSUE TITLE
Cannot reconstruct results

### ISSUE THREAD

**Issue by Amaroun** [fvacek/quickbox#60]
For example if real start time is shifted against planed one for any reason. Moving zero time after some of the races read out theirs cards, there is no way to I know of to fix results so all racers have same zero start time to create equal results.

**Comment by fvacek** [comment]
Yes they shall. This can be easily managed. Even if starter shift 00, correct time can be still entered to QuickEvent before first runner enters finish. This is always about 15 minutes of time to correct starter fault.

**Comment by Amaroun** [comment]
Yea, but if first runners reads out and you suddenly see first split 630 + something min, because 0 time is 10:30 and you forget to edit stage start time from default, you will not get reasonable results without editing database.
Definitly an user fault, but on the other hand quite simple operation for software, but big help for mankind.

**Comment by fvacek** [comment]
First of all, organizers **always shall check twice when event really started as soon as possible**. In both cases, with proposed feature implemented or not. 

Even if you do not do it, you can set correct time and read card again, when first competitor readout is wrong.

So we can change change this issue to __it would be nice to have__ category because it is not necessary feature, rather something to solve brutal organizers incompetency.

**Comment by arnost00** [comment]
You never have problem with zero time ? Zero time can be easily moved by mistake on start.
In last two weeks I need move zero time twice after bunch of SI cards was read.
Some thing like "Result reconstruction" is needed, NOT nice to have !

**Comment by viktorm2015** [comment]
I like so. It is important function.

**Comment by fvacek** [comment]
#72 will solve this issue.
